# Generated by Django 2.2.6 on 2020-10-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('comments_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='articles',
        ),
    ]
