# Generated by Django 2.2.6 on 2020-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201005_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
