# Generated by Django 2.2.6 on 2020-10-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20201004_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments_count',
            field=models.IntegerField(null=True),
        ),
    ]
